Refactor Radio & RadioGroup components — markup, styling, stories
ebs-integrator/ebs-design pull request #438
Opened 2022-10-08 11:20 UTC by danielavornic

[Teamwork Task](https://projects.ebs-integrator.com/#/tasks/36558947)

2022-10-08 17:43 UTC, danielavornic commented
Would it be better to make Radio a compound component and use Radio.Group instead of RadioGroup?

2022-10-17 19:51 UTC, marcellefter requested changes
Not sure if the Radio and RadioGroup components should be in different folders, they share at least some types. We should to consider keeping them the more closely.

2022-10-17 19:51 UTC, marcellefter commented on src/components/Radio/Radio.scss
> +    &--radio-align {
Align is a modifier and should be like size without `radio` word because it's taken from the context.
```&--left, &--right```

2022-10-17 19:51 UTC, marcellefter commented on src/components/Radio/Radio.scss
> +      border-width: 1px;
Write the short version of the border

2022-10-17 19:51 UTC, marcellefter commented on src/styles/variables.scss
> +$radio-spacing: 8px !default;
The spacing is referred to the radio group, change to `$radio-group-spacing`

2022-10-18 07:50 UTC, danielavornic commented
> Not sure if the Radio and RadioGroup components should be in different folders, they share at least some types. We should to consider keeping them the more closely.

What about implementing a compound component? Radio.Group?

2022-10-26 13:18 UTC, marcellefter approved these changes

2022-10-26 13:18 UTC, merged